#!/bin/bash

echo "🚀 Flurfunk Database Setup"
echo "=========================="
echo ""
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Name: 'flurfunk'"
echo "4. Choose your region"
echo "5. Set a strong password"
echo "6. Wait for project creation (2-3 minutes)"
echo ""
echo "7. Once created, go to SQL Editor"
echo "8. Copy the contents of 'api/db/schema.sql'"
echo "9. Paste and click 'Run'"
echo ""
echo "10. Go to Settings → API"
echo "11. Copy these values:"
echo "    - Project URL"
echo "    - anon public key"
echo ""
echo "12. Create .env.local with:"
echo "    SUPABASE_URL=your-project-url"
echo "    SUPABASE_ANON_KEY=your-anon-key"
echo ""
echo "✅ Done! Your backend is ready."